# Generated by Django 4.2.1 on 2023-05-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_file_name_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
    ]
